system/app/Http/routes.php
<?php

Route::get('/', ['as' => 'root', 'uses' => 'FinalTasksController@index']);
Route::resource('final_tasks', 'FinalTasksController');

Route::get('/upload/csv', ['as' => 'upload_csv', 'uses' => 'FinalTasksController@uploadCsv']);
Route::post('/upload/csv', ['as' => 'store_csv', 'uses' => 'FinalTasksController@storeCsv']);

system/app/FinalTask.php
<?php

namespace IndeksTugasAkhir;

use DB;
use File;
use Illuminate\Database\Eloquent\Model;

use Carbon\Carbon;
use League\Csv\Reader;

class FinalTask extends Model
{
  protected $fillable = ['title', 'student_name', 'nim', 'department_id', 'date', 'rate', 'score', 'comment'];

  public function department()
  {
    return $this->belongsTo('IndeksTugasAkhir\Department');
  }

  public static function storeCsv($file) {
    $filename = time() . ".csv";
    $file->move('.', $filename);
    $reader = Reader::createFromPath($filename);

    $final_tasks = collect([]);
    $is_header_found = false;
    foreach ($reader as $index => $row) {
      if (strtoupper($row[0]) == "NO") {
        $is_header_found = true;
        continue;
      }

      if ($is_header_found) {
        $final_task = array(
          'student_name' => $row[1],
          'nim' => $row[2],
          'department' => $row[3],
          'date' => FinalTask::parseDate($row[4]),
          'rate' => $row[6],
          'comment' => $row[7],
          'title' => $row[8],
          'score' => $row[9],
        );
        $final_tasks->push($final_task);
      }
    }
    File::delete($filename);
    DB::transaction(function() use (&$final_tasks){
      $final_tasks->each(function($attrs){
        $final_task = FinalTask::where('nim', $attrs['nim'])->first();
        $department = Department::where('name', $attrs['department'])->first();
        if ($department === null) {
          $department = new Department(['name' => $attrs['department']]);
          $department->save();
        }
        $attrs['department_id'] = $department->id;

        if (strlen($attrs['rate'] == 0)) unset($attrs['rate']);
        if ($final_task === null) {
          $final_task = new FinalTask($attrs);
          $final_task->save();
        } else {
          $final_task->update($attrs);
        }
      });
    });
  }

  public static function parseDate($dateStr) {
    $matches = array();
    $pattern1 = '/(\d{1,2}) ([a-zA-Z]+) (\d{4})/';
    $pattern2 = '/(\d{1,2})-([a-zA-Z]+)-(\d{2})/';
    $months = [
      'januari' => 1,
      'februari' => 2,
      'maret' => 3,
      'april' => 4,
      'mei' => 5,
      'juni' => 6,
      'juli' => 7,
      'agustus' => 8,
      'september' => 9,
      'oktober' => 10,
      'november' => 11,
      'desember' => 12,
    ];
    $short_months = [
      'jan' => 1,
      'feb' => 2,
      'mar' => 3,
      'apr' => 4,
      'may' => 5,
      'jun' => 6,
      'jul' => 7,
      'aug' => 8,
      'sep' => 9,
      'oct' => 10,
      'nov' => 11,
      'dec' => 12
    ];
    preg_match($pattern1, $dateStr, $matches);
    if (count($matches) == 4) {
      $year = intval($matches[3]);
      $month_name = strtolower($matches[2]);
      $month = $months[$month_name];
      $date = intval($matches[1]);
    } else {
      preg_match($pattern2, $dateStr, $matches);
      $year = intval(strlen($matches[3]) == '2' ? ('20' . $matches[3]) : $matches[3]);
      $month_name = strtolower($matches[2]);
      $month = $short_months[$month_name];
      $date = intval($matches[1]);
    }
    return Carbon::createFromDate($year, $month, $date);
  }

  public static function scoreOptions() {
    return [
      'A' => 'A',
      'B' => 'B',
      'C' => 'C',
      'D' => 'D',
      'E' => 'E'
    ];
  }
}

system/app/Http/Controllers/FinalTasksController.php
<?php

namespace IndeksTugasAkhir\Http\Controllers;

use Illuminate\Http\Request;
use IndeksTugasAkhir\Http\Requests;
use IndeksTugasAkhir\Http\Controllers\Controller;

use Carbon\Carbon;
use IndeksTugasAkhir\Department;
use IndeksTugasAkhir\FinalTask;
use IndeksTugasAkhir\Http\Requests\CreateFinalTaskRequest;
use IndeksTugasAkhir\Http\Requests\UpdateFinalTaskRequest;

class FinalTasksController extends Controller
{

    public function index(Request $request)
    {
        $search = $request->get('search');
        $final_tasks = FinalTask::orderBy($search['type'] ? $search['type'] : 'created_at', $search['type'] ? 'asc' : 'desc');
        if ($search) {
            $final_tasks = $final_tasks->where($search['type'], 'LIKE' , "%" . $search['query']. "%");
        }
        $final_tasks = $final_tasks->paginate(20);
        $pagination = $final_tasks->render();
        $pagination = str_replace("/?", "?", $pagination);
        return view('final_tasks.index', compact('search', 'final_tasks', 'pagination'));
    }

    public function create()
    {
        $final_task = new FinalTask();
        $department_options = Department::options();
        $score_options = FinalTask::scoreOptions();
        return view('final_tasks.create', compact('final_task', 'department_options', 'score_options'));
    }

    public function store(CreateFinalTaskRequest $request)
    {
        $final_task = new FinalTask($request->all());
        if (!$request->get('rate')) {
            $final_task->rate = null;
        }
        $final_task->save();
        return redirect()->route('root');
    }

    public function show($id)
    {
        $final_task = FinalTask::find($id);
        return $final_task;
    }

    public function edit($id)
    {
        $final_task = FinalTask::find($id);
        $department_options = Department::options();
        $score_options = FinalTask::scoreOptions();
        return view('final_tasks.edit', compact('final_task', 'department_options', 'score_options'));
    }


    public function update(UpdateFinalTaskRequest $request, $id)
    {
        $final_task = FinalTask::find($id);
        $final_task->update($request->all());
        if (!$request->get('rate')) {
            $final_task->rate = null;
            $final_task->save();
        }
        return redirect()->route('root');
    }

    public function destroy($id)
    {
        $final_task = FinalTask::find($id);
        $final_task->delete();
        return redirect()->route('root');
    }

    public function uploadCsv(Request $request)
    {
        return view('final_tasks.upload_csv');
    }

    public function storeCsv(Request $request)
    {
        $file = $request->file('csv_file');
        $filename = FinalTask::storeCsv($file);
        return redirect()->route('root');
    }
}

system/resources/views/final_tasks/_form.blade.php
{!! Form::hidden('id', null) !!}
<div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
  <div class='col-sm-12'>
    {!! Form::label('title', 'Judul Tugas Akhir') !!}
    {!! Form::text('title', null,  ['class' => 'form-control']) !!}
    {!! $errors->first('title', '<span class="help-block">:message</span>') !!}
  </div>
</div>

<div class="form-group {{ $errors->has('nim') ? 'has-error' : '' }}">
  <div class='col-sm-2'>
    {!! Form::label('nim', 'NIM') !!}
    {!! Form::text('nim', null,  ['class' => 'form-control']) !!}
    {!! $errors->first('nim', '<span class="help-block">:message</span>') !!}
  </div>
</div>

<div class="form-group {{ $errors->has('student_name') ? 'has-error' : '' }}">
  <div class='col-sm-6'>
    {!! Form::label('student_name', 'Nama Mahasiswa') !!}
    {!! Form::text('student_name', null,  ['class' => 'form-control']) !!}
    {!! $errors->first('student_name', '<span class="help-block">:message</span>') !!}
  </div>
</div>

<div class="form-group {{ $errors->has('department_id') ? 'has-error' : '' }}">
  <div class='col-sm-2'>
    {!! Form::label('department_id', 'Jurusan') !!}
    {!! Form::select('department_id', $department_options, null, ['class' => 'form-control']) !!}
    {!! $errors->first('department_id', '<span class="help-block">:message</span>') !!}
  </div>
</div>

<div class="form-group {{ $errors->has('date') ? 'has-error' : '' }}">
  <div class='col-sm-2'>
    {!! Form::label('date', 'Tanggal') !!}
    {!! Form::text(null, null, ['class'=>'form-control', 'id' => 'date', 'readonly'=>'true']) !!}
    {!! Form::hidden('date', $final_task->date, ['id' => 'date_hidden']) !!}
    {!! $errors->first('date', '<span class="help-block">:message</span>') !!}
  </div>
</div>

<div class="form-group {{ $errors->has('rate') ? 'has-error' : '' }}">
  <div class='col-sm-2'>
    {!! Form::label('rate', 'Rate') !!}
    {!! Form::number('rate', null,  ['class' => 'form-control']) !!}
    {!! $errors->first('rate', '<span class="help-block">:message</span>') !!}
  </div>
</div>

<div class="form-group {{ $errors->has('score') ? 'has-error' : '' }}">
  <div class='col-sm-2'>
    {!! Form::label('score', 'Nilai') !!}
    {!! Form::select('score', $score_options, null,  ['class' => 'form-control']) !!}
    {!! $errors->first('score', '<span class="help-block">:message</span>') !!}
  </div>
</div>

<div class="form-group {{ $errors->has('comment') ? 'has-error' : '' }}">
  <div class='col-sm-6'>
    {!! Form::label('comment', 'Komentar') !!}
    {!! Form::textarea('comment', null,  ['class' => 'form-control']) !!}
    {!! $errors->first('comment', '<span class="help-block">:message</span>') !!}
  </div>
</div>

<div class="form-group">
  <div class='col-sm-3'>
    {!! Form::Submit('Simpan', ['class' => 'btn btn-primary btn-save']) !!}
  </div>
</div>

<script type="text/javascript">
$("#date").datepicker({
  format: 'dd MM yyyy',
  language: 'id',
  autoclose: true
})
.on('changeDate', function(){
  var dt = $("#date").datepicker('getUTCDate');
  var month = dt.getUTCMonth()+1 < 10 ? "0" + (dt.getUTCMonth()+1) : dt.getUTCMonth()+1;
  var date = dt.getUTCDate() < 10 ? "0" + dt.getUTCDate() : dt.getUTCDate();
  dt = dt.getUTCFullYear() + "-" + month + "-" + date + " 00:00:00";
  $("#date_hidden").val(dt);
});
</script>

system/resources/views/final_tasks/_search_form.blade.php
{!! Form::open(['method' => 'GET', 'route' => ['root'], 'class' => 'form-inline', 'id' => 'search_form']) !!}
  <div class="form-group">
    {!! Form::select('type', [
      'nim' => 'NIM',
      'student_name' => 'Nama Mahasiswa',
      'title' => 'Judul Tugas Akhir'
    ], $search['type'] ? $search['type'] : 'name', ['class'=>'form-control', 'id' => 'search_type']); !!}
  </div>
  <div class="form-group">
    <div class="input-group">
      {!! Form::text('query', $search['query'] ? $search['query'] : null,  ['id' => 'search_query', 'class' => 'form-control input-large', 'size' => 50]) !!}
      <span class="input-group-btn">
        {!! Form::button('<i class="glyphicon glyphicon-search"></i>', ['class' => 'btn btn-primary', 'type' => 'submit', 'id' => 'search_button']) !!}
      </span>
    </div>
  </div>
{!! Form::close() !!}

system/resources/views/final_tasks/_table.blade.php
<table class="table table-bordered table-striped table-condensed">
  <thead>
    <tr>
      <th width="1%">#</th>
      <th>Judul Tugas Akhir</th>
      <th>NIM</th>
      <th>Nama Mahasiswa</th>
      <th>Jurusan</th>
      <th>Tanggal</th>
      <th>Rate</th>
      <th>Nilai</th>
      <th width="1%"></th>
    </tr>
  </thead>
  <tbody>
  @if(count($final_tasks) == 0)
    <tr>
      <td colspan="9" align='center'>
        <i>Belum ada tugas akhir yang terdaftar.</i>
      </td>
    </tr>
  @endif

  @foreach($final_tasks as $index => $final_task)
    <tr>
      <td>{{ $index+1 + $final_tasks->perPage() * ($final_tasks->currentPage()-1) }}</td>
      <td>{{ $final_task->title }}</td>
      <td>{{ $final_task->nim }}</td>
      <td>{{ $final_task->student_name }}</td>
      <td>{{ $final_task->department? $final_task->department->name : '-' }}</td>
      <td>{{ indo_date($final_task->date) }}</td>
      <td>{{ $final_task->rate }}</td>
      <td>{{ $final_task->score }}</td>
      <td>
        {!! Form::open(['method' => 'DELETE', 'route' => ['final_tasks.destroy', $final_task], 'style' => 'display:inline;']) !!}
          {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-sm confirmation', 'msg' => 'Apakah anda yakin ingin menghapus data berikut?', 'title' => 'Hapus']) !!}
        {!! Form::close() !!}
        <a href="{{ route('final_tasks.edit', $final_task) }}" class='btn btn-primary btn-sm' title='Edit'>
          <i class='glyphicon glyphicon-edit'></i>
        </a>
        @if ($final_task->comment)
          <a class='btn btn-info btn-sm btn-detail' title='Lihat Komentar' id='{{ $final_task->id }}'>
            <i class='glyphicon glyphicon-comment'></i>
          </a>
        @endif
      </td>
    </tr>
  @endforeach
  </tbody>
</table>
{!! $pagination !!}

<div class="modal fade" id='modal_detail' role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title">Komentar Tugas Akhir</h3>
      </div>
      <div class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Kembali</button>
      </div>
    </div>
  </div
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('body').on('click', '.btn-detail', function(){
      var id = $(this).attr('id');
      $.ajax({
        url:'{{ route('final_tasks.show', null) }}/' + id,
        dataType: 'json',
        success: function(response){
          $('#modal_detail .modal-body').html(response.comment);
          $('#modal_detail').modal('show');
        }
      });
    });
  });
</script>

system/resources/views/final_tasks/create.blade.php
@extends('layouts.guest')

@section('content')
<h1>Tambah Data Tugas Akhir</h1>
<hr>
{!! Form::open(['route'=>'final_tasks.store', 'class' => 'form-horizontal', 'role' => 'form']) !!}
  @include('final_tasks._form')
{!! Form::close() !!}

<script type="text/javascript">
var date = new Date();
$("#date").datepicker('setDate', date);
</script>
@stop

system/resources/views/final_tasks/edit.blade.php
@extends('layouts.guest')

@section('content')
<h1>Edit Tugas Akhir</h1>
<hr>
{!! Form::model($final_task, ['method' => 'PATCH', 'route'=>['final_tasks.update', $final_task], 'class' => 'form-horizontal', 'role' => 'form']) !!}
  @include('final_tasks._form')
{!! Form::close() !!}
<script type="text/javascript">
var date = new Date({{ carbon_date($final_task->date)->timestamp * 1000 }});
$("#date").datepicker('setDate', date);
</script>
@stop

system/resources/views/final_tasks/index.blade.php
@extends('layouts.guest')

@section('content')
  <div class='row'>
    <div class='col-md-12'>
      @include('final_tasks._search_form')
      <br>
      <a href="{{ route('upload_csv') }}" class='btn btn-primary'>
        <i class='glyphicon glyphicon-upload'></i>
        Upload (.csv)
      </a>
      <a href="{{ route('final_tasks.create') }}" class='btn btn-primary'>
        <i class='glyphicon glyphicon-plus'></i>
        Tambah Data
      </a>
      <hr>
      <div class='table-responsive'>
        @include('final_tasks._table')
      </div>
    </div>
  </div>
@stop

system/resources/views/final_tasks/upload_csv.blade.php
@extends('layouts.guest')

@section('content')
  <div class='row'>
    <div class='col-md-12'>
      <h1>Upload Daftar Tugas Akhir (.csv)</h1>
      <hr>
      {!! Form::open(['url' => route('store_csv'), 'files' => true]) !!}
        <div class='form-group'>
          {!! Form::file('csv_file', ['accept'=>'.csv']) !!}
        </div>
        <div class='form-group'>
          {!! Form::submit('Kirim', ['class'=>'btn btn-primary']) !!}
        </div>
      {!! Form::close() !!}
    </div>
  </div>
@stop